#!/bin/bash

# DISPAK
#
# Simple tool to manage code and servers/services easily.
#
# Source code and documentation: https://github.com/Amaury/Dispak
#
# © 2017, Amaury Bouchard <amaury@amaury.net>
#
# Licensed under the terms of the MIT license (see LICENSE file).

# ########## GLOBAL VARIABLES (readable by rules' code) ##########

# Path to the Dispak installation root directory.
# @type	string
DPK_ROOT="$(cd "$(dirname "$(readlink "${BASH_SOURCE[0]}" || echo "${BASH_SOURCE[0]}")")" && pwd)"

# List of options given on the command-line.
declare -A DPK_OPTIONS

# Name of the asked command to execute
COMMAND=$1

# Path to the root of the current git repository.
GIT_REPO_PATH="$(git rev-parse --git-dir 2>/dev/null)"
if [ "$GIT_REPO_PATH" != "" ]; then
	GIT_REPO_PATH="$(dirname "$GIT_REPO_PATH")"
fi

# ########## INTERNAL VARIABLES ##########

# List of rules.
# @type	array
declare -a _DPK_RULES

# List of mandatory command-line parameters, indexed by rule.
declare -A _DPK_RULES_MANDATORY_PARAMS

# List of optional command-line parameters, indexed by rule.
declare -A _DPK_RULES_OPTIONAL_PARAMS

# ########## INCLUDE SOURCE FILES ##########
# functions files
. "$DPK_ROOT/lib/utils.sh"
. "$DPK_ROOT/lib/rules.sh"
. "$DPK_ROOT/lib/checks.sh"

# import rules
_dpk_import_rules "$DPK_ROOT/rules"
if [ -d "$GIT_REPO_PATH/etc/dispak-rules" ]; then
	_dpk_import_rules "$GIT_REPO_PATH/etc/dispak-rules"
fi

# ########## OPTIONS AND CONFIGURATION ##########
# no option given: show help and quit
if [ "$COMMAND" = "" ] || [ "$COMMAND" = "h" ] || [ "$COMMAND" = "help" ]; then
	rule_exec_help
	exit 0
fi
# fetch command-line options
shift
while getopts "h-:" OPTCHAR; do
	case "$OPTCHAR" in
		"-")
			KEY=$(echo $OPTARG | cut -d"=" -f 1)
			VALUE=${OPTARG#*=}
			if [ "$VALUE" = "" ]; then
				VALUE=1
			fi
			DPK_OPTIONS[$KEY]="$VALUE"
			;;
		"h")
			rule_exec_help
			exit 1
			;;
		*)
			abort "$(ansi red)Bad command line option '-$OPTCHAR'.$(ansi reset)"
			;;
	esac
done
# check if the asked command is known
CMD_FOUND=0
for _CMD in ${_DPK_RULES[@]}; do
	if [ "$_CMD" = "$COMMAND" ]; then
		CMD_FOUND=1
	fi
done
if [ $CMD_FOUND -eq 0 ]; then
	abort "$(ansi red)Unknown command $(ansi reset)'$COMMAND'$(ansi red).$(ansi reset)"
fi
# check if all mandatory options are given
for _OPT in ${_DPK_RULES_MANDATORY_PARAMS[$COMMAND]}; do
	if [ "${DPK_OPTIONS[$_OPT]}" = "" ]; then
		abort "$(ansi red)Mising parameter $(ansi reset)--$i_OPT$(ansi red).$(ansi reset)"
	fi
done
# check if extraneous parameters are given
for _OPT in "${!DPK_OPTIONS[@]}"; do
	if [ "$_OPT" = "platform" ]; then
		continue
	fi
	FOUND=0
	for _KEY in ${_DPK_RULES_MANDATORY_PARAMS[$COMMAND]} ${_DPK_RULES_OPTIONAL_PARAMS[$COMMAND]}; do
		if [ "$_KEY" = "$_OPT" ]; then
			FOUND=1
			break;
		fi
	done
	if [ $FOUND -eq 0 ]; then
		abort "$(ansi red)Extraneous parameter $(ansi reset)--$_OPT$(ansi red).$(ansi reset)"
	fi
done
# read configuration file
if [ "$GIT_REPO_PATH" != "" ]; then
	if [ -f "$GIT_REPO_PATH/dispak.conf" ]; then
		. "$(eval realpath "$GIT_REPO_PATH/dispak.conf")"
	elif [ -f "$GIT_REPO_PATH/etc/dispak.conf" ]; then
		. "$(eval realpath "$GIT_REPO_PATH/etc/dispak.conf")"
	fi
fi

# ########## EXECUTION ##########
# moving to root path
if [ "$GIT_REPO_PATH" != "" ]; then
	pushd "$GIT_REPO_PATH" > /dev/null
fi
EXEC_FUNCTION="rule_exec_${COMMAND}"
$EXEC_FUNCTION
success

